CREATE TABLE USERS(USERNAME VARCHAR(10) PRIMARY KEY NOT NULL, PASSWORD VARCHAR(10) NOT NULL);
INSERT INTO USERS VALUES ('user1','user1');
INSERT INTO USERS VALUES ('user2','user2');
INSERT INTO USERS VALUES ('user3','user3');
INSERT INTO USERS VALUES ('user4','user4');


CREATE TABLE IDENTITIES(UID INT PRIMARY KEY NOT NULL, DISPLAYNAME VARCHAR(15) NOT NULL, EMAIL VARCHAR(30));
